### ISSUE TITLE
Class 'Mobile_Detect' not found

### ISSUE THREAD

**Issue by nbapp** [thomascube/roundcube-elastic4mobile#2]
After installing the plugin, the following error message occurs:
PHP Fatal error:  Class 'Mobile_Detect' not found in mydomain.com/plugins/elastic4mobile/elastic4mobile.php on line 19

**Comment by thomascube** [comment]
That class should be installed automatically when you install the plugin using composer (as described at https://plugins.roundcube.net). If you installed it another way, you need to manually install the dependencies.

**Comment by nbapp** [comment]
Retried, but keep the error.
A solution for me: `require_once 'vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php';` in elastic4mobile.php

**Comment by thomascube** [comment]
Mobile_Detect should be registered in Composer's autoload mapping. I don't know why this doesn't happen on your system but it's not a bug of this plugin and we can't do much about it.

Try running `php composer.phar dump-autoload` and check `vendor/composer/autoload_classmap.php`.

**Comment by eilandert** [comment]
I have the same problem.

Running "composer require mobiledetect/mobiledetectlib" solved the issue, but Mobile_detect clashes with xframework. 

AH01071: Got error 'PHP message: PHP Fatal error:  Cannot declare class Mobile_Detect, because the name is already in use in /var/www/html/plugins/xframework/vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php on line 23
